/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionista.Vistas;

/**
 *
 * @author vico_
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPaciente = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmDieta = new javax.swing.JMenu();
        jmDietaComida = new javax.swing.JMenuItem();
        jmComidas = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jmSeguimiento = new javax.swing.JMenu();
        jmiPaciente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem10.setText("jMenuItem10");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        jmPaciente.setText("Paciente");
        jmPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPacienteActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Formulario paciente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jmPaciente.add(jMenuItem9);

        jMenuBar1.add(jmPaciente);

        jmDieta.setText("Dieta");
        jmDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDietaActionPerformed(evt);
            }
        });

        jmDietaComida.setText("Formulario dieta comida");
        jmDietaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDietaComidaActionPerformed(evt);
            }
        });
        jmDieta.add(jmDietaComida);

        jMenuBar1.add(jmDieta);

        jmComidas.setText("Comidas");
        jmComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmComidasActionPerformed(evt);
            }
        });

        jMenuItem11.setText("Formulario comida");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmComidas.add(jMenuItem11);

        jMenuBar1.add(jmComidas);

        jmSeguimiento.setText("Seguimiento");
        jmSeguimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSeguimientoActionPerformed(evt);
            }
        });

        jmiPaciente.setText("Por paciente");
        jmiPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPacienteActionPerformed(evt);
            }
        });
        jmSeguimiento.add(jmiPaciente);

        jMenuItem2.setText("Por dieta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmSeguimiento.add(jMenuItem2);

        jMenuBar1.add(jmSeguimiento);

        jmSalir.setText("Salir");
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPacienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmPacienteActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioPaciente fp = new FormularioPaciente();
        fp.setVisible(true);
        Escritorio.add(fp);
        Escritorio.moveToFront(fp);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jmDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDietaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jmDietaActionPerformed

    private void jmComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmComidasActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jmComidasActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint();
        FormularioComidas fc = new FormularioComidas();
        fc.setVisible(true);
        Escritorio.add(fc);
        Escritorio.moveToFront(fc);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Escritorio.removeAll();
        Escritorio.repaint();
        FormularioSeguimiento fs = new FormularioSeguimiento();
        fs.setVisible(true);
        Escritorio.add(fs);
        Escritorio.moveToFront(fs);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmDietaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDietaComidaActionPerformed
        // TODO add your handling code here:
         Escritorio.removeAll();
        Escritorio.repaint();
        FormularioDietaComida fdc = new FormularioDietaComida();
        fdc.setVisible(true);
        Escritorio.add(fdc);
        Escritorio.moveToFront(fdc);
    }//GEN-LAST:event_jmDietaComidaActionPerformed

    private void jmSeguimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSeguimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmSeguimientoActionPerformed

    private void jmiPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPacienteActionPerformed
        // TODO add your handling code here:
           Escritorio.removeAll();
        Escritorio.repaint();
        FormularioHistorial fdh = new FormularioHistorial();
        fdh.setVisible(true);
        Escritorio.add(fdh);
        Escritorio.moveToFront(fdh);
    }//GEN-LAST:event_jmiPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jmComidas;
    private javax.swing.JMenu jmDieta;
    private javax.swing.JMenuItem jmDietaComida;
    private javax.swing.JMenu jmPaciente;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenu jmSeguimiento;
    private javax.swing.JMenuItem jmiPaciente;
    // End of variables declaration//GEN-END:variables



public void IrAEscritorio() {
        Escritorio.removeAll();
        Escritorio.repaint();
    }






}
